config/routes.rb
Bookmeoff::Application.routes.draw do
  root 'bookings#index'

  get 'bookings/range', to: 'bookings#range'
  resources :bookings



  get 'approvals' => 'approvals#index'
  patch 'approvals/approve/:id' => 'approvals#approve'

  post 'auth/:provider/callback' => 'auth#success'
  get 'auth/logout'
  get 'auth/new'

  get 'users/show/:id' => 'users#show'

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase



  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  validates :from, presence: true
  validates :to, presence: true

  validate :from_date_must_be_earlier_than_to_date

  def from_date_must_be_earlier_than_to_date
    errors.add(:from, 'must be earlier than to') if
        from != nil && to != nil && from > to
  end
  belongs_to :user, :class_name => 'User',
             :foreign_key => 'user_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :manager, :class_name => 'User',
             :foreign_key => 'user_managed_by_id'

  has_many :bookings

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless current_user
      redirect_to '/auth/new' # halts request cycle
    end
  end
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  def index
    @bookings = Booking.where(approved: false).where.not(user_id: current_user.id)
  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.approved = true

    if @booking.save
      redirect_to approvals_path
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  protect_from_forgery except: :success

  skip_before_action :require_login

  def new

  end

  def success
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(approved: true)
  end

  def range
    @bookings = Booking.where "\"from\" BETWEEN :start_date AND :end_date OR \"to\" BETWEEN :start_date AND :end_date ",
                              {:start_date => params[:start], :end_date => params[:finish]}

    render :json => @bookings.as_json(:include => :user)
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.approved = false

    @user.bookings << @booking
    if @user.save
      redirect_to @booking
    else
      render 'new'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update(params[:booking].permit( :from, :to))
      redirect_to @booking
    else
      render 'edit'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path
  end
  private
    def booking_params
      params.require(:booking).permit( :from, :to)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/approvals/index.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <th>User</th>
    <th>From</th>
    <th>To</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Approve</th>
  </thead>

  <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.name %></td>
        <td><%= booking.from %></td>
        <td><%= booking.to %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Delete', booking_path(booking),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <%= link_to 'Approve', 'approvals/approve/%d' % booking.id,
                      method: :patch, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>

app/views/booking/index.html.erb
<h1>Book holidays!</h1>
<p>This is the calendar</p>
<a href="/booking/request">Request time off</a>

app/views/booking/request.html.erb
Request

app/views/bookings/_form.erb
<%= form_for @booking do |f| %>
    <% if @booking.errors.any? %>
        <div id="errorExplanation">
          <h3><%= pluralize(@booking.errors.count, "error") %> prohibited
            this booking from being saved:</h3>
          <ul>
            <% @booking.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <label><%= current_user.name %></label>
    </div>
    <div class="form-group">
      <%= f.label :from %><br>
      <%= f.text_field :from, :class => "form-control from" %>

    </div>
    <div class="form-group">
      <%= f.label :to %><br>
      <%= f.text_field  :to, :class => "form-control to" %>
    </div>
    <%= f.submit 'Book it!', :class => "btn btn-default" %>
<% end %>

app/views/bookings/edit.erb
<h1>Edit book time off</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<div ng-app>
  <div>
    <div class="form-group pull-right">
      <%= link_to 'Request time off', new_booking_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <div ng-controller="calendarController" id="calendar" >
    <h1>{{month()}} {{year}}</h1>

    <button ng-click="goToPreviousMonth()" class="btn btn-default">
      <span class="glyphicon glyphicon-chevron-left"></span> Previous
    </button>

    <button ng-click="goToNextMonth()" class="btn btn-default">
      Next <span class="glyphicon glyphicon-chevron-right"></span>
    </button>

    <div id="calendar-header">
      <div>Monday</div>
      <div>Tuesday</div>
      <div>Wednesday</div>
      <div>Thursday</div>
      <div>Friday</div>
      <div>Saturday</div>
      <div>Sunday</div>
    </div>

    <div class="clear"></div>

    <div ng-repeat="day in days">
      <div class="day" ng-class="{'not-this-month': day.isNotThisMonth}">
        <span>{{day.value}}</span>
        <ul class="list-unstyled">
          <li ng-repeat="booking in day.bookings"><span class="label label-primary"><a href="/bookings/{{booking.id}}">{{booking.who}}</a></span></li>
        </ul>
      </div>
      <div ng-hide="($index+1) % 7" class="clear"></div>
    </div>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="page-header">
  <h1>book time off</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<h1>Show booking</h1>
<p>
  <strong>Who:</strong>
  <%= @booking.user.name %>
</p>

<p>
  <strong>From:</strong>
  <%= @booking.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @booking.to %>
</p>

<%= link_to 'Back', bookings_path %> | <%= link_to 'Edit', edit_booking_path(@booking) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book holidays!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapsable">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span class="navbar-brand">Holidays</span>
  </div>

  <div class="collapse navbar-collapse" id="navbar-collapsable">
    <% if $has_auth_provider %>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-left">
          <li><a href="/">Bookings</a></li>
          <li><a href="/approvals">Approvals</a></li>
          <li><a href="/users">Users</a></li>
        </ul>
        <p class="nav navbar-text navbar-right">Welcome, <strong><%= link_to current_user.name, '/users/show/%d' % current_user.id %></strong>! <%= link_to "Not you?", "/auth/logout" %></p>
      <% else %>
          <ul id="user" class="nav navbar-nav navbar-right">
            <li>
                  <a href="/auth/ldap"><i class="glyphicon glyphicon-lock"></i>&nbsp;Sign in</a>
            </li>
          </ul>
      <% end %>
    <% end %>
  </div>

</nav>
<div class="container">

<%= yield %>

</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :holidayDaysLeft %><br>
      <%= f.text_field :holidayDaysLeft %>
    </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="users-index" ng-controller="usersControl">

  <table class="table table-bordered table-striped">
    <thead>
      <th>Username</th>
      <th>Managed By</th>
    </thead>
    <tr ng-repeat="user in users">
      <td>{{user.name}}</td>
      <td>
        <div class="current-manager">
          <div ng-if="user.hasManager">
              <a href='#'>Nobody</a>
          </div>
          <div ng-if="!user.hasManager">
              {{user.manager}} <a href='#'>Change</a>
          </div>
        </div>
        <div class="change-manager">
          <input type="text" ng-model="" />
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>Holidays Requested</h1>
</div>

<p>
  <Strong>Requested Holidays</Strong>
<table class="table table-bordered table-striped">
  <thead>
    <th>User</th>
    <th>From</th>
    <th>To</th>
    <th>Approved</th>
  </thead>
  <tbody class="list">
  <% @user.bookings.each do |booking| %>
      <tr>
        <td><%= booking.who %></td>
        <td><%= booking.from %></td>
        <td><%= booking.to %></td>
        <td><%= booking.approved %></td>
      </tr>
  <% end %>
  </tbody>
</table>
</p>